baseURL = 'http://example.org/'
languageCode = 'id'
title = 'My New Hugo Site'
paginate = 10
theme = "resume"

[params]
address = "Cikunir, Bekasi Selatan"
email = "adelesmanahutabarat@gmail.com"
favicon = "/favicon.ico"
firstName = "Ade"
lastName = "Lesmana"
phone = "0822-7251-8485"
profileImage = "img/me.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/ade-lesmana-hutabarat/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/adelesmanahutabarat/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"